name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Deploy
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      run: |
        cd ~/glenn &&
        git config --global user.email "support@top.gg" &&
        git config --global user.name "Glenn" &&
        git fetch --all &&
        git reset --hard origin/master &&
        echo "DISCORD_TOKEN=$DISCORD_TOKEN" > .env &&
        npm install &&
        node .
      

    # steps:
    # - uses: actions/checkout@v2
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: ${{ matrix.node-version }}
    # - run: echo "DISCORD_TOKEN=$DISCORD_TOKEN" > .env
    # - run: npm install
    #   env:
    #     DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
    # - run: pm2 kill && pm2 start . -n "Glenn"