name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: echo "DISCORD_TOKEN=$DISCORD_TOKEN" > .env
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
    - run: pm2 kill
    - run: pm2 start . -n "Glenn"
    - run: sleep 20 && tail -20 ~/.pm2/logs/Glen-out.log
